use_frameworks!

platform :ios, '10.0'

target 'TDXModule_Example' do
  pod 'TDXModule', :path => '../'

  target 'TDXModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
